<a href="https://colab.research.google.com/github/dominickmalzone/sleepsearch-backend/blob/main/general_search_intents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import re 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns ; sns.set()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline


In [ ]:
import json
with open('sleepsearch_intents.json') as file:
  data = json.load(file)

In [ ]:
df = {'tag' : [], 'pattern' : []}

for intent in data['intents'] :
  tag = intent['tag']
  for pattern in intent['patterns'] :
    df['tag'].append(tag)
    df['pattern'].append(pattern)

df = pd.DataFrame(df)
df

tag           pattern
0          minecraft         minecraft
1          minecraft              mcpe
2          minecraft    minecraft game
3          minecraft  mojang minecraft
4    covid19_summary           covid19
..               ...               ...
391             uber         uber cars
392             lyft              lyft
393             lyft         lyft jobs
394             lyft        lyft price
395             lyft         lyft cars

[396 rows x 2 columns]

In [ ]:
df = df.sample(frac = 1) 
df

tag                    pattern
12          hackathon      hackathon competition
300          linkedin            linkedin trends
198        javascript                 javascript
376          apple tv                   apple tv
289           twitter                    twitter
..                ...                        ...
361           spotify               spotify jobs
344       rich people                rich people
340             tesla                      tesla
69        sleep apnea      sleep apnea treatment
161  microsoft office  microsoft office products

[396 rows x 2 columns]

In [ ]:
# # One hot encode labels
# from sklearn.preprocessing import OneHotEncoder
# one_hot_encoder = OneHotEncoder(sparse=False)
# tag_one_hot = one_hot_encoder.fit_transform(df["tag"].to_numpy().reshape(-1, 1))
# tag_one_hot

# Extract labels ("target" columns) and encode them into integers 
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
tag_encoded = label_encoder.fit_transform(df["tag"].to_numpy())
tag_encoded

array([32, 43, 39,  8, 84, 47, 30, 59, 27, 39, 75,  2, 68, 44, 17, 34, 71,
       82, 16, 43, 38, 22, 32, 27, 90,  9, 17, 18, 15, 68, 89, 58,  3, 20,
       92, 33, 65, 40, 10, 20, 46, 23, 70, 48, 21, 15,  0,  2, 53, 18, 53,
       17, 40, 71, 40, 18, 81, 22, 30, 87, 33, 67, 65, 32, 42, 13, 67, 54,
       45, 70, 80, 73, 68, 71, 46,  8, 83, 52, 13, 66, 19, 82, 57, 28, 79,
       35,  5, 90, 25, 86, 10,  0,  9, 26, 46,  1, 37, 90, 16, 63,  4, 89,
       77, 58, 63, 15, 91, 12, 66, 65, 51, 61, 35, 70, 50, 67, 41, 48, 92,
       33,  3, 86, 66, 29, 63, 33, 20, 69, 29, 73, 38, 31, 21, 25, 36, 50,
        8, 71, 91, 81, 64,  7, 56, 52,  7, 25, 77, 85, 45, 10, 52, 12, 83,
       64, 59, 55, 23, 64, 11, 88, 87, 48, 28, 60, 51, 92, 48, 77, 86, 69,
       83, 81, 22, 19, 65, 50, 18, 26, 82, 33, 13, 55, 92, 37, 84, 61,  4,
       91, 27, 46, 72, 86,  4, 21,  6, 89,  7, 17, 14, 79, 23, 52, 87,  5,
        3, 76, 44, 42, 62, 28, 42, 44, 27, 42, 19, 89, 53, 16, 53, 64, 76,
       14, 55, 60, 69, 77

In [ ]:
# 0 = corona virus
# 1 = hackathon
# 2 = minecraft

In [ ]:
train_sentences = df.pattern.to_numpy()
train_tag = tag_encoded
train_sentences,train_tag

(array(['hackathon competition', 'linkedin trends', 'javascript',
        'apple tv', 'twitter', 'microsoft jobs', 'google cloud software',
        'node projects', 'github jobs', 'javascript projects',
        'stackoverflow answers', 'airbnb rooms', 'CEOs',
        'liver cancer symptoms', 'coronavirus', 'html', 'slack',
        'tsunami natural disaster', 'cat cute', 'linkedin jobs',
        'java coding', 'earthquake disaster', 'hackathon league', 'github',
        'world war 2 casualties', 'arduino website', 'covid19',
        'cryptocurrency trends', 'cancer treatment',
        'rich people net worth', 'world war 1 famous people',
        'netflix jobs', 'amazon trends', 'django', 'youtube music music',
        'heart cancer disease', 'react', 'kidney cancer symptoms',
        'brain cancer', 'django library', 'lyft jobs',
        'excessive daytime sleepiness symptoms',
        'shift work disorder treatment', 'microsoft access', 'dog cute',
        'cancer causes', 'adobe creat

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create a pipeline
model_0 = Pipeline([
  ("tf-idf", TfidfVectorizer()),
  ("clf", MultinomialNB())
])

# Fit the pipeline to the training data
model_0.fit(X=train_sentences, 
            y=train_tag);

In [ ]:
model_0.score(X=train_sentences,
              y=train_tag)

0.9318181818181818

In [ ]:
class_names = label_encoder.classes_
class_names

array(['adobe creative cloud', 'adobe xd', 'airbnb', 'amazon',
       'amazon prime', 'angular', 'apple', 'apple music', 'apple tv',
       'arduino', 'brain cancer', 'breast cancer', 'c', 'c#', 'c++',
       'cancer', 'cat', 'covid19_summary', 'cryptocurrency', 'css',
       'django', 'dog', 'earthquake', 'excessive daytime sleepiness',
       'express', 'facebook', 'flask', 'github', 'gmail', 'google',
       'google cloud', 'google play', 'hackathon', 'heart cancer', 'html',
       'hulu', 'insomnia', 'instagram', 'java', 'javascript',
       'kidney cancer', 'kotlin', 'laravel', 'linkedin', 'liver cancer',
       'lung cancer', 'lyft', 'microsoft', 'microsoft access',
       'microsoft excel', 'microsoft office', 'microsoft onenote',
       'microsoft outlook', 'microsoft powerpoint', 'microsoft word',
       'minecraft', 'mouse', 'narcolepsy', 'netflix', 'node',
       'objective c', 'parasomnia', 'php', 'python', 'rat', 'react',
       'restless legs syndrome', 'revolutions', 'ri

In [ ]:
sentence = "stomach cancer"
predict =  model_0.predict([sentence])
probability = model_0.predict_proba([sentence])

probability[0][predict], class_names[predict]
# 0 = corona virus
# 1 = hackathon
# 2 = minecraft

(array([0.24547778]), array(['stomach cancer'], dtype=object))

In [ ]:
# export
import pickle
with open('model_0.pkl', 'wb') as model_file:
  pickle.dump(model_0, model_file)

In [ ]:
# load
loaded_model = pickle.load(open("model_0.pkl", 'rb'))
result = loaded_model.score(train_sentences, train_tag)
print(result)

0.9318181818181818


In [ ]:
loaded_model.predict(['ahdhaa'])

array([77])